
name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: boons8858
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: boons8858/${{ github.event.repository.name }}
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md
